name = "kookykraft"
author = "mystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68d1f4d8c4d6d036eced9410d0e323086a23f999f88042bc16ca43eecfbf734c"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
