name = "kookykraft"
author = "mystic"
version = "3.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "868af3759b36a616432893dd7738adff32481a0143d3017c1b7f39029832ce35"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21"]
