name = "kookykraft"
author = "mystic"
version = "3.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd6995476508a93280ba816a24a1eab18d35d7d5b37cbb6be43ab9cd4ec823bc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21"]
