name = "kookykraft"
author = "mystic"
version = "3.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0d622b29a92d9fa230dd99ef4233dcce13e580d8f1caf4cf1d68ef84339ce5e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21"]
